### ISSUE TITLE
CSV YouTube-Import

### ISSUE THREAD

**Issue by C-O-D** [SkyTubeTeam/SkyTube#1007]
The YouTube data import in CSV format in V. 2.979 still doesn't work although the release notes say it should. Is this a misunderstanding by me?

**Comment by C-O-D** [comment]
SkyTube Extra 2.980 still doesn't import abo.csv.
It simply does nothing after selecting the file and after two or three tries it crashes...
Can this PLEASE PLEASE PLEASE be fixed?

**Comment by saebaryo-xyz** [comment]
Same issue with latest version on android 11

**Comment by L31FY** [comment]
https://github.com/SkyTubeTeam/SkyTube/issues/1033

**Comment by C-O-D** [comment]
SkyTube Extra 2.981 still doesn't import abo.csv!
AND still not even one response from the developer!
I mean, that's such an important feature, I don't get it...

**Comment by gzsombor** [comment]
Probably duplicate of #1046
