### ISSUE TITLE
YouTube Videos not loading / download not working either

### ISSUE THREAD

**Issue by ff1992ff** [SkyTubeTeam/SkyTube#1025]
Skytube Version 2.979 Extra
Android Version 11

Recently (about 1 or 2 days ago), videos started to not load with the default videoplayer. Activity tracker keeps spinning, but no reaction. Comments in the right hand panel however do load.

**Comment by maaaat** [comment]
Same issue with NewPipe.

**Comment by eternalprisms** [comment]
Skytube Version 2.979 Extra
Android Version 11

I've come across the same issue default player which stopped working for playing videos. However, videos play when switching the video player preference to "Official".

**Comment by RandomModderJDK** [comment]
You also can't download, I think this is pretty related. It is like that I think two days ago. So no new issue(would be cool if you maybe edit the title, that both isn't working).

**Comment by gzsombor** [comment]
It seems, it's more widespread. I'm going to create a release in the next hours, until that, you can try the snapshot builds : https://github.com/SkyTubeTeam/SkyTube/actions/runs/1781071893

(It would be nice, if those snapshot could automatically update themself after installation :wink: )

**Comment by eternalprisms** [comment]
Just updated to v2.980 and is working perfectly.
Thank you and the Skytube Team for the work that you do with maintaining this application 🤝
