### ISSUE TITLE
Translate/Localize SkyTube's website

### ISSUE THREAD

**Issue by milotype** [SkyTubeTeam/SkyTube#1031]
**Is your feature request related to a problem? Please describe.**
[SkyTube's website](https://skytube-app.com/) is only in english. As I don't know where you host the website, I'm making this feature request here.

**Describe the solution you'd like**
Make SkyTube's website multilingual. 
- if possible, simply add a new component within the [SkyTube](https://hosted.weblate.org/projects/skytube/) project (named for instance **Website**) at Hosted Weblate with the necessary source strings
- ideally, enable the site to recognize the user's/browser's locale settings, or add a dropdown menu for selecting languages

If you decide to support localized versions of the website, consider to change the `class="description"` by adding the information about mutliliguality in the heading section, for instance:

`<p class="description"><a href="https://github.com/ram-on/SkyTube">SkyTube</a> is an alternative, free, multilingual, open-source YouTube application for Android.  It allows you to use YouTube comfortably without the need for Google/YouTube account and hence this app only offers read-only access to YouTube.</p>`

Also, if possible, add a new "feature-item" about mutliliguality in the website's **Feature** section after the _Bookmarks_ div, for instance:

```
<div class="media feature feature-item" onclick="document.getElementById('featuresScreen').src='assets/img/screenshots/languages.jpg'">
	<div class="media-body">
		<i class="fa fa-bookmark fa-2x pull-left"></i>
		<h3 class="media-heading">Multilingual</h3>
		Use the app in your language.
	</div>
</div>
```

I do not have Android so I'm sorry not to be able to provide an image for the suggested "languages.jpg".

**Comment by milotype** [comment]
Please excuse, the new "feature item" should have the class **fa-language**, not **fa-bookmark** ...

So the div would be:

```
<div class="media feature feature-item" onclick="document.getElementById('featuresScreen').src='assets/img/screenshots/languages.jpg'">
	<div class="media-body">
		<i class="fa fa-language fa-2x pull-left"></i>
		<h3 class="media-heading">Multilingual</h3>
		Use the app in your language.
	</div>
</div>
```

**Comment by drogga** [comment]
@milotype @gzsombor
The site no longer exist, so this ticket is unnecessary and can be closed.
