### ISSUE TITLE
 YouTube無廣告

### ISSUE THREAD

**Issue by chingmulee** [SkyTubeTeam/SkyTube#1038]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drogga** [comment]
@gzsombor Please close and maybe even delete this pointless issue ticket if you can...

BTW, the nothing plays since today, NP fixed the issue 2+ hours ago, please update the extractor or whatever is needed...
Thank You.

**Comment by gzsombor** [comment]
Thanks, I've noticed too!
