### ISSUE TITLE
Skytube extra on Galaxy S10 stacked with other games in game center

### ISSUE THREAD

**Issue by warp123** [SkyTubeTeam/SkyTube#1042]
**Describe the bug**
I gave installed the extra version from git hub,  but every time I install it, the icon it classified as a game and I can only access it through game center. 

**To Reproduce**
1. Download APK from git and install

**Expected behavior**
Should not be recognized as a game 

**Screenshots**

**Setup:**
 - Android version: 12
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source: Downloaded from GitHub
 - App Version: v2.980
 - App Flavour: Extra

**Additional context**

**Comment by drogga** [comment]
#764

**Comment by gzsombor** [comment]
Yes, I think, this is more of a Samsung bug, than a SkyTube bug. Of course, if you know, how to fix, please open a pull request, thanks!
