### ISSUE TITLE
Videos not playing on 2.980 Extra (default player)

### ISSUE THREAD

**Issue by ff1992ff** [SkyTubeTeam/SkyTube#1054]
Hi everybody!
I assume YouTube probably has changed something again on their side making videos not load with SkyTube again. I am on 2.980 Extra and I use the default player. If I open a video the loading symbol just keeps spinning with nothing happening at all. Comments load with no issues, but downloading a video doesn't work either. I also forced the app to stop running and tried restarting it again, but no success. The app behavior can be replicated on my second device...

I hope everyone is enjoying the holidays! Happy easter and thank you for your help!

**Comment by atomjack** [comment]
I was getting this as well. @gzsombor I can confirm your commit an hour ago fixed it! Much appreciated!

**Comment by gzsombor** [comment]
Luckily, it was fixed by NewPipe developers :)
