### ISSUE TITLE
ADD global video speed setting 

### ISSUE THREAD

**Issue by allanlaal** [SkyTubeTeam/SkyTube#1068]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by allanlaal** [comment]
should not overwrite  #1067 if set for video

**Comment by ShareASmile** [comment]
@gzsombor this issue can be closed as completed in PR #1085

**Comment by gzsombor** [comment]
Thanks @ShareASmile , you are right, this is already released!
