### ISSUE TITLE
New version 2.983 seems to be broken now in android 4.4.4

### ISSUE THREAD

**Issue by pgpierremb2** [SkyTubeTeam/SkyTube#1116]
No feed loading, no search results, no video playback & loading comments crashes app. Is android KitKat support dropped?

**Comment by gzsombor** [comment]
The newer OkHttp client, I will release a new one ASAP

**Comment by gzsombor** [comment]
Fixed in https://github.com/SkyTubeTeam/SkyTube/pull/1118
