### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by FelipeDrytven** [SkyTubeTeam/SkyTube#1122]
Please add Skytube player subtitles support, without the need to use the official youtube. The app is wonderful, absolutely fantastic. I greatly appreciate the "Whitelist" option.

**Comment by ruegnueg** [comment]
Yeah, we definitely need subtitles. Staying on newpipe till then.

**Comment by gzsombor** [comment]
It's requested a couple of times, and it's a well known missing feature - the oldest bug seems to be #89
