### ISSUE TITLE
The channels are empty, the videos don't show up \ load there anymore

### ISSUE THREAD

**Issue by drogga** [SkyTubeTeam/SkyTube#1127]
YT added or "introduced" two new \ additional tabs in channels, "Live" and "Shorts", which broke the "Videos" tab in SkyTube and even in every instance of invidious, but while the second might get fixed sooner or later, SkyTube might never will, because it seems left-out to die unfortunately, and @gzsombor and if there are any other active contributors (it doesn't seem like there is) doesn't actually uses the app every single day as the main source of consuming YT content, but only to test a few changes from time to time (like every other month or even more), else the constant error toast messages that are being thrown\shown would've been fixed by now, long time ago, when I included all of them in another issue ticket, but at this point, I doubt that he, or anyone cares at all and is even able \ can fix those...

BTW, Vanced \ ReVanced or NewPipe are not a good alternatives for me for a number of reasons, which doesn't makes sense to mention here and is pointless. I don't expect SkyTube to be maintained at all much longer, the minSDKversion was bumped \ increased and nothing got better or improved, just as how I expected and wrote many times, which was pointless change, so when it dies completely, IDK what the .... will I use then, since nothing compares to SkyTube as of simplicity, because I don't need fancy features, like being able to watch in HDR, 360° or any other BS, for this, we have that heavy garbage - the YouTube app\site, so watching YT will become a lot complicated and overall bad experience and a nightmare for me, even compared to now, with the constant toast messages that pop-up as soon as you search for something or try to load channel's videos, I guess I will use it until the subscriptions still load and the most videos do still play, which might change any moment from now...

**Comment by DanielGlaas** [comment]
Maybe this is related to https://github.com/TeamNewPipe/NewPipe/issues/9223

**Comment by gzsombor** [comment]
I've regularly use SkyTube, but haven't had problem, so thanks for looking up and finding a relevant ticket in NewPipe/NewPipeExtractor. I've created a new release with the latest NewPipeExtractor.

**Comment by drogga** [comment]
@gzsombor Thank you.
They load now, but I don't believe you that you are actually and regularly using the app on a real device and not in emulator(s), because it's just impossible that you haven't faced any of the issues and the annoying toast messages that we, the rest of us all get.

BTW, the changelog dialog that pops-up when you update is annoying and kind of pointless, please get rid of it.

There's no need to create a discussion topic for every new release, since no one cares and it only pointlessly fills the tab with unnecessary topics, making it more hard to notice\find the manually created ones by the users.

At least 5 of the screenshot images in the readme are broken, also there are no icons for the 2 apps in F-Droid, IDK why, but it's like this for some months now.

**Comment by drogga** [comment]
@gzsombor I think that the actions workflow (android.yml) file in the Legacy repo should probably be adjusted a bit, since it seems is the same as this one here, making it invalid and it (the task) doesn't run over there...

**Comment by drogga** [comment]
@ram-on @gzsombor
The project's site is dead, probably that's why some images don't load in the readme, IDK who manages it, but if it won't be online (alive) anymore at all and ever again, please remove the link(s) to it form the short description here and wherever else mentioned and try to outsource the dead images or remove them. Thank You !

**Comment by drogga** [comment]
@ram-on @gzsombor
The project's site is dead, probably that's why some images don't load in the ReadMe, IDK who manages it, but if it won't be online (alive) anymore at all and ever again, please remove the link(s) to it form the short description here and wherever else mentioned and try to outsource the dead images, or reLink them from\to https://github.com/SkyTubeTeam/SkyTube/tree/master/screenshots, or remove the dead ones that lead to the site and are not also available here from the ReadMe. Thank You !

**Comment by drogga** [comment]
@ram-on @gzsombor
The project's site is dead, probably that's why some images don't load in the ReadMe, IDK who manages it, but if it won't be online (alive) anymore at all and ever again, please remove the link(s) to it form the short description here and wherever else mentioned, like in the app(s) about screen \ menu [Preferences>About>Website] and try to outsource the dead images, or reLink them from\to https://github.com/SkyTubeTeam/SkyTube/tree/master/screenshots, or remove the dead ones from the ReadMe that lead to the site and are not also available here. Thank You !

**Comment by drogga** [comment]
**This issue isn't entirely fixed, as the Live and Shorts videos are still not shown in the channels !**
@gzsombor - Please make them show up in the "Videos" tab or create 2 more tabs for "Live" and "Shorts".

**Comment by drogga** [comment]
**This issue isn't entirely fixed, as the "Live" and "Shorts" videos are still not shown in the channels !**
@gzsombor - Please make them show up in the "Videos" tab or create 2 more tabs for them.

**Comment by gzsombor** [comment]
Yes, the website is fully managed by @ram-on AFAIK, so we can't do anything, if he or the site disappears.

**Comment by drogga** [comment]
@gzsombor Can you also remove the site from the organization /SkyTubeTeam page and from inside the app and every other place ?

Also, Shorts and Live videos don't show up in Trending and Featured tabs, I don't think that there's a need or makes sense to create a different - new issue ticket for this, or any of the other things I commented here, which you seems like ignored...
