### ISSUE TITLE
Subscribers Videos not listed in tab "Video" 

### ISSUE THREAD

**Issue by Musicbox1965** [SkyTubeTeam/SkyTube#1128]
In the application Sky Tube Extra,
Subscribers Videos are not listed in tab "Video" 
I tried refresh and: restart the Smartphone, stop the application, erased cache.

Any solution ?

Thanks in advance 🙏

**Comment by drogga** [comment]
Same as mine (#1127), next time please search or sort by "recently updated" before creating a duplicate issue ticket.

Can be closed.

**Comment by gzsombor** [comment]
If it's the same problem, it will be solved by the recent release.
