### ISSUE TITLE
A proper TimeStamp support is needed !

### ISSUE THREAD

**Issue by drogga** [SkyTubeTeam/SkyTube#1136]
Currently when clicking \ tapping on a TimeStamp (can also be called "chapters") which are mostly provided in the description of longer videos, it just opens the same video on top of the current one in a new player window activity, that plays simultaneously alongside the previous origin one, but also plays from the beginning, instead of jumping to that time point in the first place, the timestamps from \ in the comments are completely ignored and not supported (highlighted \ clickable) at all in SkyTube.

**Comment by gzsombor** [comment]
yeah, that would be nice!

**Comment by gzsombor** [comment]
Thanks for closing it, yes, this is released in https://github.com/SkyTubeTeam/SkyTube/releases/tag/v2.986
