### ISSUE TITLE
Jitpack OkHttpClient Dependency can't be resolved when Building

### ISSUE THREAD

**Issue by RandomModderJDK** [SkyTubeTeam/SkyTube#1144]
**Describe the bug**
I cloned the repo. When I try to create a simple build this error popes up:
`Could not parse POM https://jitpack.io/com/github/SkyTubeTeam/components/okhttp-client/v0.0.5/okhttp-client-v0.0.5.pom`
`> Could not find com.github.SkyTubeTeam.components:components:v0.0.5.`

**To Reproduce**
1. `git clone https://github.com/SkyTubeTeam/SkyTube.git`
2. `./gradlew build`

**Expected behavior**
A clean build with all dependencies resolved should appear

**Screenshots**
If applicable, add screenshots to help explain your problem, or the link for the video, where You've found the issue

**Setup:**
 - Java running: OpenJDK 17
 - OS: Linuxmint 21.1 Vera

**Additional context**
Apparently the reason for gradle to search after the com.github.SkyTubeTeam.components:components:v0.0.5 dependency instead of the correct com.github.SkyTubeTeam:components:v.0.0.5 is the wrong groupId in this pom:
https://jitpack.io/com/github/SkyTubeTeam/components/okhttp-client/v0.0.5/okhttp-client-v0.0.5.pom
I don't know why Jitpack does this get wrong, because in the original repo it's fine.

**Comment by gzsombor** [comment]
Thanks for the report, I'm not sure, what and how this has changed, but changing the version number to 0.0.5 seems to be fixed the problem.
