### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by ruegnueg** [SkyTubeTeam/SkyTube#1181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by drogga** [comment]
#89 & #1122

**Comment by drogga** [comment]
So you know that this is a duplicate, but still created it and on top of that, your are too lazy to fill the issue template ?

**Comment by drogga** [comment]
So you know that this is a duplicate, but still created it and on top of that, your are too lazy to fill the issue template ?

@gzsombor Pls close this.

**Comment by gzsombor** [comment]
Yes, it's a duplicate, thx for noticing.
