### ISSUE TITLE
Can not select "USA" as content country in the settings

### ISSUE THREAD

**Issue by sudo-splinter-cell** [SkyTubeTeam/SkyTube#1223]
"Default content country" setting does not have USA as an option. The default "system" option is available probably because people living in the USA will keep it in default, however, outside the USA, it should be possible to select USA as an option. This directly affects the "trending videos" section of the app. Outside the USA, it is impossible to see what is trending in the USA.

**Comment by gzsombor** [comment]
Fixed in #1249
