### ISSUE TITLE
Video Downloads only work at 720

### ISSUE THREAD

**Issue by SyCoREAPER** [SkyTubeTeam/SkyTube#1225]
**Describe the bug**
Video Downloads are not at "Best Quality" but rather 720. Any override causes an error. 

**To Reproduce**
1. Go to desired video 
2. Click on Download
3. Scroll down to N/A
4. See error: Video Downloaded is a fraction of the size it should be. 

**Expected behavior**

**Setup:**
 - Android version: 14
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source: Downloaded from GitHub
 - App Version: 2.987
 - App Flavour: Extra

**Additional context**
If predefined resolutions are set, an error of "Cannot find any video streams within the requested xyz Resolution" is shown. If you leave them blank and set only 'Best Quality' it downloads as 720.

**Comment by SyCoREAPER** [comment]
Example url https://youtu.be/WO2b03Zdu4Q

**Comment by zqysurj** [comment]
Now quality is even lower now : 360p maximum
