### ISSUE TITLE
Can't select USA as default content country 

### ISSUE THREAD

**Issue by jkpathan** [SkyTubeTeam/SkyTube#1227]
**Describe the bug**
I am in Pakistan. I can select any other country for default content country but USA is not on the list. If I select System as default, UK is selected. 

**To Reproduce**
1. Go to Preferences - Video Player - Default content country 
2. Scroll through the list, there is no USA 

**Expected behavior**
United States should be on the list 

**Setup:**
 - Android version: 13
 - Is Your device rooted? Yes
 - Do You use Tor or any VPN service with your device? NO
 - App source [e.g. FDroid, Downloaded from GitHub, self build] Fdroid
 - App Version [e.g. v2.977] 2.987
 - App Flavour [e.g. Extra or OSS] OSS

**Comment by gzsombor** [comment]
Fixed in #1249
