### ISSUE TITLE
Refreshing Trending page results in infinite loading icon.

### ISSUE THREAD

**Issue by wolfie7679** [SkyTubeTeam/SkyTube#1242]
**Describe the bug**

**To Reproduce**
1. Open the app
2. In trending feed scroll up to trigger the "refresh"
3. notice loading icon turning indefinitely.

**Expected behavior**
Refresh function should work and the loading icon should disappear when either:

a refresh timeout has happened.

refresh successful.

**Screenshots**
--

**Setup:**
 - Android version: [e.g. 7 or 10, etc] 7 and 14
 - Is Your device rooted? No
 - Do You use Tor or any VPN service with your device? No
 - App source [e.g. FDroid, Downloaded from GitHub, self build] Downloaded from GitHub
 - App Version [e.g. v2.977] 2.987
 - App Flavour [e.g. Extra or OSS] Extra

**Additional context**

New installation on S23 Ultra.

Was able to reproduce on android 7 emulator and android 14 emulator

**Comment by gzsombor** [comment]
Fixed by #1259
