### ISSUE TITLE
Problem with playing anything in SkyTube

### ISSUE THREAD

**Issue by borba0** [SkyTubeTeam/SkyTube#1244]
Hello.
I'm newbee, so please be patient and understanding ;)
I'm an owner of an old Android radio in my car. It's built on IceCreamSandwich (4.0.4). And, of course, there is no option for update/upgrade official firmware.
HondaConnect (yes, I know, the old one).
Through last 5 years, as I'm an owner, I used to play YT via SkyTube.
But from month ago it's impossible.
In each version (older/newer) still got the same info "Channel information cannot be retrieved. Could not parse JSON". 
I've tried with/without google mainframes (which slows down the system till crashing), but there is no possibility to play as usual songs/films.
App (2.987) starts normally, load the most popular videos on the dashboard, but in every case I would like to play anything, there is only one announcement.
Is there any option still to use SkyTube on my so old system?
Thanks in advance.

**Comment by mckaygerhard** [comment]
this is a issue for [SkyTubeLegacy](https://github.com/SkyTubeTeam/SkyTubeLegacy) so can be closed here..
