### ISSUE TITLE
Latest version "Sharing" no longer works

### ISSUE THREAD

**Issue by gitmatt19** [SkyTubeTeam/SkyTube#1255]
I use skytube to "share" to Kodi, which has worked fine up until I upgraded today to 2.988

**To Reproduce**

Share video to "Kore" app which forwards to Kodi to play video.

**Expected behavior**
Nothing happens after sharing it appears no URL is getting sent.

**Setup:**
 - Android version: 6
 - Is Your device rooted? yes
 - Do You use Tor or any VPN service with your device? no
 - App source skytube extra
 - App Version Todays release
 - App Flavour Extra 

Would like links to previous versions so I can downgrade.

**Comment by gzsombor** [comment]
Interestingly, this works for me - the app selector come up when I click on the 'Share via...', for videos and for downloaded videos too. Can you provide more information, how this happens, how do you get to that non-working Share menu item?
 You can download any releases from https://github.com/SkyTubeTeam/SkyTube/releases

**Comment by gitmatt19** [comment]
For share I click the 3 dots on the video and share menu item and it brings up all the apps to share with then I select "Play on Kodi" and it has always sent it to Kodi to play. Downgraded to the previous version and it works again but I get a upgrade nag everytime I start the app.

**Comment by zqysurj** [comment]
I wiped app data, then tried to share this video
https://www.youtube.com/watch?v=NPqDIwWMtxg
through "share via" and "copy URL", the link given by skytube is
https://www.youtube.com/https://www.youtube.com/channel/UC3lBXcrKFnFAFkfVk5WuKcQ
That may explain why sharing to kodi doesn't work

**Comment by gzsombor** [comment]
Fix released
