### ISSUE TITLE
Can't install version 2.988

### ISSUE THREAD

**Issue by TruongTanLuc201270** [SkyTubeTeam/SkyTube#1257]
**Screenshots**
If applicable, add screenshots to help explain your problem, or the link for the video, where You've found the issue
![Screenshot_20240501-072018](https://github.com/SkyTubeTeam/SkyTube/assets/145727083/8a296ae5-4038-41f9-88a3-2e300da11178)
![Screenshot_20240501-072027_Package installer](https://github.com/SkyTubeTeam/SkyTube/assets/145727083/8c9e8f14-92b3-4808-9220-6ae19830cf4c)

**Setup:**
 - Android version: 9
 - Is Your device rooted? - Yes, Samsung Galaxy S7 Canada
 - App source: Downloaded from GitHub
 - App Version 2.988
 - App Flavour: OSS
I have two devices: Sony KD-49X7500F & Samsung Galaxy S7 Canada rooted, but cannot install.

**Comment by gzsombor** [comment]
From this alone, it's really hard to find the reason, what went wrong in the installer

**Comment by drogga** [comment]
@TruongTanLuc201270 You are not trying to install over a build from F-droid right ?, I have no idea what it says ("not installed" probably), so when you use text from somewhere, attach a screenshot or a screen record, always make sure to be in English.
Anyway, you can try with https://github.com/Aefyr/SAI and paste the English text from the reason, including the full error one.

**Comment by TruongTanLuc201270** [comment]
SkyTube version 2.987 in F-Droid but version 2.988 not have yet.

**Comment by drogga** [comment]
I Knwo. So 2.987 you've previously install and have is from F-Droid ?, if Yes, then you are getting a signature mismatch, because unless you have patches (Xposed/Magisk Modules) , you cannot install one over the other, because they are using different signatures, F-Droid uses thir own and the GitHub releases are signed by gzsombor's signature.

**Comment by drogga** [comment]
I have not idea what you mean, please type in a translator in the language you are sure you know, translate it to English and then post it here, because it's hard for someone to understand you.

**Comment by TruongTanLuc201270** [comment]
The only fix: Uninstall this app from downloaded F-Droid than reinstall from GitHub.
