### ISSUE TITLE
Copying of urls does not work

### ISSUE THREAD

**Issue by RandomModderJDK** [SkyTubeTeam/SkyTube#1270]
**Describe the bug**
The url of a video, which you receive to share is not valid. It just contains the channel.

Example invalid url:
https://www.youtube.com/https://www.youtube.com/channel/UCKvfzCyVQPe2IYg4PkugvWQ

**To Reproduce**
1. Go to any youtube video
2. Click on the three points
3. Click Copy Url
4. Paste the url somewhere
5. See invalid url

**Expected behavior**
That the url is like this:
https://youtu.be/7MoipvBda_8
Or this: 
https://www.youtube.com/watch?v=7MripvBda_8

**Setup:**
 - Android version: 12
 - Is Your device rooted? Nope
 - Do You use Tor or any VPN service with your device? Nope
 - App source [e.g. FDroid, Downloaded from GitHub, self build] Github
 - App Version v 2.988 (29.04.2024)
 - App Flavour Extra

**Additional context**
-

**Comment by drogga** [comment]
Related to #1255 and supposedly fixed with commit 5d6785e7cd6b8abc461b2b14a7c1f3a21fa32e8b, which will be available in `v2.989`, according to the milestone.

**Comment by gzsombor** [comment]
Thanks for the report @RandomModderJDK , and the investigation @drogga , yes, you are right, this problem is already fixed!
