### ISSUE TITLE
Error 403 (all videos)

### ISSUE THREAD

**Issue by Darknir23** [SkyTubeTeam/SkyTube#1274]
![Screenshot_20240709-163056](https://github.com/SkyTubeTeam/SkyTube/assets/175214994/a5af3b85-ca77-4110-85d5-5a5c0ab1db2b)

**Comment by Samylol99** [comment]
Btw this is duplicate of #1273 eveyone is having this issue because yt updated something with it's code that makes current extraction flawed

**Comment by gzsombor** [comment]
I'm closing as duplicate
