### ISSUE TITLE
New version 2.988 problem to open any video

### ISSUE THREAD

**Issue by SiampanisP** [SkyTubeTeam/SkyTube#1277]
App Android 2.988 can not locate any video to play. 
Result is 404 can't open video URL.

**Comment by SiampanisP** [comment]
Correction Response 403 not 404

**Comment by mckaygerhard** [comment]
duplicate of #1278  close it please

**Comment by mckaygerhard** [comment]
duplicate of https://github.com/SkyTubeTeam/SkyTube/issues/1273 please close it

**Comment by SiampanisP** [comment]
Reopen and closed as not planned
I don't understand Turkish.
English please.
