### ISSUE TITLE
The description covers my entire screen in horizontal mode

### ISSUE THREAD

**Issue by Loleman11** [SkyTubeTeam/SkyTube#1286]
**Describe the bug**
When watching a video in horizontal mode on the app, opening the description covers the entire screen, and there's no way to close it to continue watching the video normally.

**To Reproduce**

Open the app.
Select any video and start playing it.
Rotate your phone to horizontal mode.
Open the video description.
The description covers the entire screen, making it impossible to watch the video.
Expected behavior
I expected the description to appear as an overlay that could be closed or minimized so I could continue watching the video without obstruction.

**Additional context**

This issue makes it difficult to view the video content once the description is opened. A fix to make the description closable or appear as a non-intrusive overlay would be greatly appreciated.
![Photo](https://github.com/user-attachments/assets/02f81e20-e8eb-44ce-9f9b-0f10dbc7d1ea)

**Comment by drogga** [comment]
Known UX problem and a nonsense (and the gestures cannot be disabled separately), you should rotate to portrait to be able to swipe it down and avoid facing this issue by slowly and gradually swipe it up, which should stop to the half of the screen, then it should hide even if you tap outside of it on the screen, the same for the comments bar/sheet.

**Comment by drogga** [comment]
Can you please create a new issue tickets for the missing avatars (seen in your screenshot) and the multilingual audios not being in En (mrBeast videos for example) for the dash formats and the inability to pick which one to play or make it in ENg, unless you watch in 360p (old format) ?
Thank You in advance.
