### ISSUE TITLE
V2.989 (oss) - error 403 might be back (unable to open video)

### ISSUE THREAD

**Issue by KlaasVogel** [SkyTubeTeam/SkyTube#1289]
**Describe the bug**
Black screen when starting a video. After a while error 403 pops up. (same as in V2.988)

**To Reproduce**
Start any video

**Expected behavior**
Video should start/play ;-)

**Screenshots**
Black screen

**Setup:**
 - Sony Bravia 4K GB (Android TV)
 - Android version: 9
 - Is Your device rooted? No
 - No VPN / tor
 - Self build and later also with F-Droid
 - App Version [e.g. v2.989]
 - App Flavour [OSS]

**Additional context**

**Comment by Samylol99** [comment]
This is awful... You are probably right.

**Comment by dagofr01** [comment]
Funny, I created negative thumbs...is that a feature ?
I have the 403 too 🙁

**Comment by gzsombor** [comment]
A bigger NewPipeExtractor fix was merged recently, I'm hopeful this will fix the problem, again. The new v2.990 version is released, please try it out!
