### ISSUE TITLE
Feature request: set playback speed

### ISSUE THREAD

**Issue by fluffynuts** [SkyTubeTeam/SkyTube#243]
Absolutely the only feature that keeps me from making this my default client is that I normally play videos at 1.5x (sometimes 1.25x). So I'd really appreciate the ability to alter playback speed, like in the official app.

**Comment by azzamsa** [comment]
Come here for one reason : Youtube Andorid app permission become more more horrible.

This is the only feature I need, playback speed. For now I watch youtube using firefox android.



Permission | Improvement from Permissions
-- | --
Record audio | Enables video recording and live streaming within the app.
Precise location | Allows you to more easily attach location information to your  videos and live streams. Also allows for features such as improved  recommendations and ads. Your precise location is never shared with  advertisers.
Read contacts | Helps find people for you to share videos with.
Receive SMS | Simplifies additional verification of your phone number that  you need to access some advanced features, including live streaming,  long uploads, and sharing.
Send SMS | Enables sending an invitation to share via SMS.
Read phone number | Allows YouTube to optimize the experience for some mobile data plans which include special rates for video.
System alert window | Allows video live streaming from other apps, such as mobile games.

**Comment by ram-on** [comment]
@azzamsa It will soon be implemented

**Comment by mblais** [comment]
I would also love to see it implemented 🙏

**Comment by BaconCatBug** [comment]
Any news on this? Its the one thing preventing me from using this app.

**Comment by gekxs** [comment]
Realy need this feature.

**Comment by Thorsky24** [comment]
@ram-on is the implementation still planned? It's also the only feature I need to use SkyTube instead of the YouTube app

**Comment by BaconCatBug** [comment]
I just gave up on waiting and use Vanced instead

**Comment by azzamsa** [comment]
I don't want to ruin the party. But why I never heard of https://github.com/TeamNewPipe/NewPipe. Since commenting on this issue on Mar 18, 2018, I can't life without playback speed. Sadly I have to use proprietary youtube client for more than 4 months, hope newpipe gives me a new hope.

**Comment by farverio** [comment]
@ram-on can you provide an update? Love the UI/ux of the app and believe this feature would make it a far superior YouTube alternative compared to newpipe.

Is there a challenging implementing that we can help with?

**Comment by BaconCatBug** [comment]
Just use Youtube Vanced

**Comment by GoatPlushie** [comment]
@BaconCatBug Vanced doesn't have channel blocking, though.

**Comment by fluffynuts** [comment]
I've moved on to NewPipe (get it from f-Droid) which does speed adjustment and download and a bunch of things. Not sure if it does channel blocking.

**Comment by gzsombor** [comment]
It's implemented at least a year ago, just forgot to close this ticket
