### ISSUE TITLE
Automatically play the next video in channel's video list OR playlist

### ISSUE THREAD

**Issue by vsudakov** [SkyTubeTeam/SkyTube#290]
If to open any channel - there are 3 tabs: "Videos", "Playlists" and "About".
The idea is to automatically play the next video in a list despite it was opened on "Videos" tab or in any "Playlist".
Also there should be an option to play the entire list repeatedly OR some single video repeatedly.

**Comment by gzsombor** [comment]
You can play the same video repeatedly for a while, but the rest autoplay is not yet implemented. There is already a couple open tickets about it: #648
