### ISSUE TITLE
[Feature Request] Pause/Resume with Bluetooth

### ISSUE THREAD

**Issue by ode79** [SkyTubeTeam/SkyTube#359]
When using Skytube and being interrupted I have to take my phone out of my pocket, focus the app and hit the pause button. This is slow.  I would like to be able do the same as I can with my podcast app, hit the pause button on my Bluetooth adapter for my headphones, which I can do much faster.

Would you consider adding the ability to pause/play the current video with Bluetooth events?

Thanks for your help.

**Comment by alexanderadam** [comment]
I'm  not quite sure whether it's related or not but it would be nice to pause and resume via keyboard as well(i.e. space key / shortcuts like in other media player).

**Comment by JamesSwift** [comment]
Any progress on this? It seems like a basic feature to support.

**Comment by gzsombor** [comment]
It seems, that no one cared enough to contribute an implementation yet, shouldn't seems too difficult, the patches are alwasy welcomed! :wink:

**Comment by Monoblaster** [comment]
Adding onto this. It seems trying to pause q video from android's media tab in the quick menu doesn't work.

**Comment by darksworm** [comment]
play/pause controls are covered by release [v2.978](https://github.com/SkyTubeTeam/SkyTube/releases/tag/v2.978)

**Comment by allanlaal** [comment]
can confirm, works
