### ISSUE TITLE
Make search available right from the start

### ISSUE THREAD

**Issue by jidanni** [SkyTubeTeam/SkyTube#386]
Make sure to allow people to search without having to enter the menu and select search first.

At least when they touch the app name it should become a search box.

**Comment by MarcoIeni** [comment]
Sorry, I didn't understand. What you are saying is that when you open the app the keyboard appears and you start typing? I would not like this because most of the times I just scroll my feed. 

If this is not what you are saying, right now the search box is at the top easily accessible.

**Comment by jidanni** [comment]
OK but I'm sure the user can type some search string into YouTube app's search box in less steps...

**Comment by MarcoIeni** [comment]
Open the app -> tap on the search button. It's one tap, the same as the official YouTube client.

**Comment by MarcoIeni** [comment]
Ok, on my 5" display I don't have this problem, maybe you have a smaller device.
We could write something like "SkyTube+" instead of the longest "SkyTube Extra" in the title bar. In this way you will see the search button I think.

**Comment by jidanni** [comment]
![screenshot_20181105-135713](https://user-images.githubusercontent.com/1230959/47980483-cff62780-e102-11e8-915d-b22274684bbe.jpg)

**Comment by jidanni** [comment]
ASUS ZenFone 3 ZE552KL.

**Comment by gzsombor** [comment]
Currently, there is a search icon on the header, so I think this bug is invalid
