### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by mcmurphy8097234789** [SkyTubeTeam/SkyTube#399]
To my understanding, skytube (not extra) uses the (open source) Youtube Android API to enable the playback of Youtube's videos. Please correct me if I am wrong

Lately, there has been an up and rising API from the invidio.us player (which in turn has its code in things like FreeTube, PeerTube, etc). So far, peertube uses it and they have made claims that the player (and I am assuming thus the API) are far more private than the default Youtube android API. 

Would it be possible/worthwhile to switch the API's? Or give an option in 'settings' to choose one or the other?

Thanks for reading

link to invidio.us: https://github.com/omarroth/invidious

**Comment by gzsombor** [comment]
If this api is only a proxy between youtube, and SkyTube, without adding support for other services (like PeerTube, vimeo, twitch, etc...), I don't see as a big improvement - but if some one implements it, with flag to enable/disable it, I think, this can be added to SkyTube.
 But generally, I think, it would be better, if this is implemented in NewPipeExtractor level, and refactor SkyTube to use NewPipeExtractor everywhere, and remove the Youtube Android API jars - or make it optional.
