### ISSUE TITLE
[Bug] Sometimes No Content Loads

### ISSUE THREAD

**Issue by rebekah65** [SkyTubeTeam/SkyTube#405]
I am using SkyTube Extra 2.93 on android 5 and 8.
Sometimes when you open SkyTube Extra there's no content under any tabs.

**Comment by alexanderadam** [comment]
@rebekah65 I had the same once and I'm sure it was because the rate limit on the shared API key was hit. I created and added an API key for my account and I had no problems since then.

**Comment by gzsombor** [comment]
I'm not sure if this is relevant anymore, if yes, please reopen with more information, how to reproduce

**Comment by drogga** [comment]
@gzsombor - we (the regular users) cannot reOpen our closed issues, we simply don't have such permission(s) !
...if I had, I could helped you with closing some outdated irrelevant ones...
