### ISSUE TITLE
Can't Open Links - Invalid URL

### ISSUE THREAD

**Issue by antonio-gil** [SkyTubeTeam/SkyTube#406]
Hi!

Since a couple of days every time that I want to open a YouTube Link it shows a notification saying that the link isn't a valid URL (see attached picture).

So far I've tried with several videos on the past couple of days, but after trying several times today, I've noted that although it fails to load a video, there are _**some**_ occasions where the video is loaded. Worth to mention that this happens regardless the URL is from `youtube.com`, `m.youtube.com` or `youtu.be`.

Also I've noticed that the search has stopped to work, and that when I load a video (from outside (when it happens), or from inside the application) it always show a notification saying that it wasn't able to download the channel information (see attached picture).

`SkyTube Version: 2.93 / 2.93 Extra`
`OS Version: Android 7.0`

![screenshot_20190123-222754](https://user-images.githubusercontent.com/9835489/51655311-bde98f80-1f61-11e9-96ef-0ac0c23c9858.jpg)
![screenshot_20190123-224046](https://user-images.githubusercontent.com/9835489/51655312-bde98f80-1f61-11e9-8423-21fb844b634b.jpg)

**Comment by absolutez3** [comment]
I experience this on Android 10 as well.

**Comment by krukai** [comment]
I have this issue as well for a few months now, using Android 10.

At first I thought only newly added videos were affected as they eventually started working (as in a few hours later), but I also encountered this issue with videos that have been uploaded several years ago.

I still need to verify if being on mobile data seems to have any impact, but other than that, is there a log to check that could help me find the issue?

Cheers!

**Comment by gzsombor** [comment]
I don't think this issue is valid currently. If you can reproduce it, please open a new ticket.
