### ISSUE TITLE
Playing problems

### ISSUE THREAD

**Issue by stemy2** [SkyTubeTeam/SkyTube#411]
Hello,

Sometimes, when i play a video, the video restarts, but the stream i'm watching doesn't stop, so the video is played with its audio stream synchronized and its audio stream since the moment where the video brutally restarted, at the same time.

I don't know if it's clear.

**Comment by kevjonesin** [comment]
I've experienced similar.

**Comment by gzsombor** [comment]
I'm not sure if this is relevant anymore, if yes, please reopen with more information, how to reproduce it.
