### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [SkyTubeTeam/SkyTube#431]
Dear skytube creator,
IMO There are some minor enhancements needed in skytube.

1 When downloading a video app should ask for the quality of the video ex 720p ,480p  before starting to download it.

2  where can i see downloading videos

3 There should be an option to filter search,
Like show playlist only or channels etc

4 An option to remove and rearrange featured and most watched and other tabs  from the main screen.

5 discussion or community tab support

**Comment by DrDonkey** [comment]
+1

**Comment by gzsombor** [comment]
It would be better to have separate tickets about these ideas, and even better would be pull requests :wink:
