### ISSUE TITLE
Playback doesn't pause if headphones disconnect

### ISSUE THREAD

**Issue by davidhedlund** [SkyTubeTeam/SkyTube#435]
Please implement pause when headphones (wired or Bluetooth) are disconnected. An option to auto-start the last station on connect would be nice too, if possible, but not as important.

**Comment by davidhedlund** [comment]
https://github.com/segler-alex/RadioDroid/issues/22

**Comment by davidhedlund** [comment]
https://github.com/deep-gaurav/MusicPiped/issues/81

**Comment by darksworm** [comment]
Looks like we should be looking out for [ACTION_AUDIO_BECOMING_NOISY](https://developer.android.com/reference/android/media/AudioManager?hl=ca#ACTION_AUDIO_BECOMING_NOISY).
I'd like to take this issue on!
