### ISSUE TITLE
(Request) Video quality

### ISSUE THREAD

**Issue by tokenmath** [SkyTubeTeam/SkyTube#604]
Videos or Lives with 1080p 60FPS or 720p 60FPS resolution do not play on SkyTube. My device supports video playback at these resolution scales

**Comment by gzsombor** [comment]
It's pretty hard to guess, what went wrong. I certainly saw errors when intermittently the app couldn't retrieve the requested stream, but unfortunately the problem disappeared a couple of minutes later, when I tried to debug it.

**Comment by tokenmath** [comment]
@gzsombor Strange since NewPipe has this resolution among other superiors. I just don't use NewPipe to watch it because I like SkyTube even more

**Comment by gzsombor** [comment]
Please provide more information, like video url, logs, etc... It's still unclear what went wrong.

**Comment by gzsombor** [comment]
The video quality selection is enhanced recently, now the app plays higher definition videos too.
