### ISSUE TITLE
Get app data folder without root

### ISSUE THREAD

**Issue by Flashwalker** [SkyTubeTeam/SkyTube#665]
Is there a way i can pull app's data folder from my non rooted  phone?

After update app is crashes on start in my xiaomi second space (and this is happens not the first time), so i wana pull favs and subs and forever forget about this app.

**Comment by gzsombor** [comment]
I don't know how to get the app's data folder, maybe, if you use adb you can get it, but I've never tried it.
 Couple of questions:
* What update braked your installation?
* Which version do you used previously?
* Do you use SkyTube Extra or the F-Droid version?
* Why can't you revert to a previous version?
* Could you check the logs, what was the error you've got?
