### ISSUE TITLE
Search Suggestions and "Trending" (US) tab instead of "Most Popular" and "Featured"

### ISSUE THREAD

**Issue by drogga** [SkyTubeTeam/SkyTube#801]
Please implement (add) a Search Suggestions (as NewPipe) and also "Trending" (US) as a tab, or just replace the "Most Popular" and "Featured" with it as they don't work\show content for me anyway (I get a API Key error toast msgs. - Android 4.3 with F-ed GApps).
Oh and I don't think that 1080p works at all... for Playback or\and DL.
Also I get a crash for no reason whatsoever after couple minutes of usage.
Keyboard should Not be in *FullScreen mode* (if you know what I mean) on Phones when the app is in Landscape !
Thanks in advance.

I'm out of options for 4.1.2 > 4.3 as of a YT client (invidious is basically dead and a bit of useless currently) and the reason i'm not using NewPipe Legacy is because it has some GApps dependencies and mine are kind of broken on 4.3, causing it to not work at all (FC on launch, clean install both Git and F-Droid vers.

**Comment by gzsombor** [comment]
Thanks for the ticket, it looks that different things are mixed together, which is not the most useful way of using the ticketing system.
I try to answer your points:
* The API key error message is a known problem, and discussed it every second ticket.
* I haven't tried 1080p, but how does it not work for you?
* Could you send the stack trace during the crash? You could use 'android-sdk/platform-tools/adb logcat', when the phone/tablet is connected over USB with developer mode activated.
* I don't know if there were anything setup in SkyTube for the keyboard, I guess, this is something which Android automatically provides - or you,as an user configured for yourself.

**Comment by drogga** [comment]
The FullScreen keyboard appears in the "Search" field only on the "Extra", and in "Enter Video URL" on both "Extra" and "Oss", on one device I use [Disable Fullscreen Keyboard](https://repo.xposed.info/module/com.shubhangrathore.xposed.disablefullscreenkeyboard) Xposed Module, but I think "keyboardHidden" should be added for both on both in their Manifest files, cuz this module does exactly this on app's runtime, without the need to mod the target \ particular app.

Since couple of days ago v2.974 & 2.975 started to refuse playing anything, so I had to update to the latest v2.978, but with it and v2.977 I get a crash: 
```
05-22 16:21:36.350  2453  4577 D Prevent : allow start activity free.rm.skytube.extra/free.rm.skytube.gui.activities.MainActivity

05-22 16:21:36.435  2453  3981 V Prevent : launch, current: [free.rm.skytube.extra]

05-22 16:21:36.435  2453  3981 D Prevent : action: start activity, package: free.rm.skytube.extra, count: 1

05-22 16:21:36.615  3809  3809 I Xposed  : Hook GoogleApiAvailability Check Success: free.rm.skytube.extra: class com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable

05-22 16:21:36.620  3809  3809 I Xposed  : Hook GoogleApiAvailability Check Success: free.rm.skytube.extra: class com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable

05-22 16:21:36.640  3809  3809 I Xposed  : DNG: Patched free.rm.skytube.extra: 0 out of 6 methods

05-22 16:21:36.800  3809  3809 I MultiDex: MultiDexExtractor(/data/app/free.rm.skytube.extra-1.apk, /data/data/free.rm.skytube.extra/code_cache/secondary-dexes)

05-22 16:21:36.805  3809  3809 I MultiDex: Blocking on lock /data/data/free.rm.skytube.extra/code_cache/secondary-dexes/MultiDex.lock

05-22 16:21:36.805  3809  3809 I MultiDex: /data/data/free.rm.skytube.extra/code_cache/secondary-dexes/MultiDex.lock locked

05-22 16:21:36.805  3809  3809 I MultiDex: MultiDexExtractor.load(/data/app/free.rm.skytube.extra-1.apk, false, )

05-22 16:21:36.920  3809  3809 I MultiDex: Extraction is needed for file /data/data/free.rm.skytube.extra/code_cache/secondary-dexes/free.rm.skytube.extra-1.apk.classes2.zip

05-22 16:21:36.925  3809  3809 I MultiDex: Extracting /data/data/free.rm.skytube.extra/code_cache/secondary-dexes/tmp-free.rm.skytube.extra-1.apk.classes-1176913987.zip

05-22 16:21:37.090  3809  3809 I MultiDex: Renaming to /data/data/free.rm.skytube.extra/code_cache/secondary-dexes/free.rm.skytube.extra-1.apk.classes2.zip

05-22 16:21:37.090  3809  3809 I MultiDex: Extraction succeeded '/data/data/free.rm.skytube.extra/code_cache/secondary-dexes/free.rm.skytube.extra-1.apk.classes2.zip': length 201501 - crc: 1607225106

05-22 16:21:37.120  3809  3809 D dalvikvm: DexOpt: --- BEGIN 'free.rm.skytube.extra-1.apk.classes2.zip' (bootstrap=0) ---

05-22 16:21:37.825  3809  3809 D dalvikvm: DexOpt: --- END 'free.rm.skytube.extra-1.apk.classes2.zip' (success) ---

05-22 16:21:37.825  3809  3809 D dalvikvm: DEX prep '/data/data/free.rm.skytube.extra/code_cache/secondary-dexes/free.rm.skytube.extra-1.apk.classes2.zip': unzip in 11ms, rewrite 709ms

05-22 16:21:38.330  2453  4581 I Xposed  : FakeGApps: returning fake signature to free.rm.skytube.extra

05-22 16:21:38.385  3809  3809 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{free.rm.skytube.extra/free.rm.skytube.gui.activities.MainActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.zzad: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.

05-22 16:21:38.695  2453  3846 I WindowManager: Screenshot max retries 4 of Token{442bae68 ActivityRecord{4416cf48 u0 free.rm.skytube.extra/free.rm.skytube.gui.activities.MainActivity}} appWin=Window{43040d80 u0 Starting free.rm.skytube.extra} drawState=4

05-22 16:21:45.495  2453  2681 D CrashAnrDetector: processName: free.rm.skytube.extra

05-22 16:21:45.495  2453  2681 D CrashAnrDetector: broadcastEvent : free.rm.skytube.extra data_app_crash

05-22 16:21:45.535  2453  3542 V Prevent : resume, current: [com.sec.android.app.launcher, free.rm.skytube.extra]

05-22 16:21:45.870  2453  3843 D Prevent : action: destroy activity, package: free.rm.skytube.extra, count: 0
```

Obviously v2.974 & 2.975 I didn't had this issue, since I used them, the "Oss" builds from here and F-Droid work too, but unfortunately there are a lot of troubles \ problems \ issues with it, and even some small differences compared to the "Extra" builds and I'm not talking about the cast and the additional player choice.
Honestly, I don't like where this project is going at all, and I can & will help you with testing and more suggestions on what to fix, if you are interested..., but currently it's basically useless for me and on older OS vers. than 4.4 KK or 5.0 LP, but it doesn't makes sense on Why would I want to use it on 5+ where it works, when I can use Official YT app, YT Vanced, NewPipe and many others anyways and avoid troubles, the point is to work for\on those where the other similar apps don't - 4.3 JB and lower, isn't it ?

v2.977 Oss barely works, and v2.978 only plays anything with the Legacy Player (unsupported), which is pointless for me to use, since there's no speed control and the volume & brightness controls are reversed, despite that the switch option is enabled, but that setting only seems to work on\in the Default Player and is ignored on\in the Legacy one for some stupid unknown reason.
The default one can't play absolutely anything in v2.978, at any resolution, no matter what.

The "Default content country" preference from the "Video Player" sub settings doesn't have the "Worldwide (All)" or "United States" (US) in the list to choose from, the "Preferred Region" under "Video Blocker" has at least the "Worldwide (All)" in it's list.
Btw, the "Default content country" one, should be moved in "Video Blocke" so the two can be at one place.

In "Oss" I had to run it without internet, so it won't crash because of the "Featured" tab, and change it to some of the other 4 in order to work, because that causes the crash there, but in the older versions there was just a toast message that the content there couldn't load, now if I manage to go to that tab without it crashing the app, it shows the refresh loading circle indefinitely, nothing loads there and it still crashes eventually.

**Comment by drogga** [comment]
I'm well aware that the Android Studio and it's Emulator images are crap and super resource hungry, I can't even download the images anymore from there, you can try some of the old x86 .iso images (which are not by google) in a VM (like "VirtualBox") or some of the very old first versions of BlueStacks or similar emulator alternative software, SkyTube doesn't have native libs, so it should work there on x86\x64 arch. As I already mentioned - I can test on "real" hardware, no problem, as long as you provide a test .apk file of "Extra", so I won't have to re\pre-install it, because it's with different Package Name from the "Oss", which works for now (v2.977) on most of my subscription videos, as long as there's MP4 stream with included \ muxed (build-in) audio inside and not separately, but it can't play live streams or anything even close to a music video in HD (only in 240p), previously I used VLC (for Android), but it's no longer able to play anything anymore and the devs of it are super lazy to fix the damn YT playback for\in EU (GDPR cookies issue).

As I already mentioned here in this ticket and countless times in some others where I commented - I mainly use it on Samsung Galaxy S3 with 4.3 Jelly Bean, I already explained the "symptoms" the best and detailed a I can [Read Carefully] !
To capture the logs only of a particular app, I use "Logcat Extreme Pro" app, and Yes, there are different options in there on how to display the logs, I like and use that one, so I don't know which one would you prefer\like, so I can pick that one from the L.E.P.'s settings, I'm afraid that that's the most detailed as it can be, after all, it's not a "traceback" of a debug build, instead it's a LogCat and that's how they usually look like, minus the formatting and the date and hour before the PID, and the letter after it, which is like a map that indicates the importance (critical, minor or whatever). Ignore the Xposed modules logs, as I always used them, nothing has changed in teh configuration on my end or got updated since the previous builds of SkyTube, which worked as it is, I simply HAVE (forced to) to use those modules, because else my system will constantly crash, being unusable without them being enabled in Xposed, because my GApps were always fucked-up.
I read it as a "cast" feature\ability or a new method in internal updates checker is causing the critical crash, it's something that you changed, reinvented \ tweaked or implemented in the past few (2-3) versions.

We already discussed the last part and what's done - is done, I no longer post all-in-one's like this (although it's super uncomfortable & pointless and it doesn't make any sense for me to create like ~13 diff. \ multiple issue tickets for basically the same similar things), but since this is my first and only one I could find and hadn't replied to your comment from 2020, I thought \ decided to add some "finishing touches" to it here, so I suggest you to read carefully, even re-read if you have to, cuz I made sure I described \ explained everything in detail.

**Comment by drogga** [comment]
Forgot to mention that if you ever touch the brightness gesture (even by mistake), you screwed, ST will never use the system's auto-brightness ever again and whenever you play a video, it will use the app's value instead (<float name="pref_key_brightness_level" value="*") from then on, making you to constantly adjust\tweak it manually from\with the gesture, ignoring the system's setting !

**Comment by drogga** [comment]
If I click/tap twice on a video it will play in another window on top of the other (stack on top of each other) and I can hear the two audio's from the 2 windows of the same video playing at the same time, it's clear that this should never happen and it can probably be fixed by restricting the player's activity to 1 instance at a time.

The playback speed drop-down doesn't always report/show the correct speed value when switching/changing between them multiple times on a single video, so you can see and hear that it's faster or slower than the indicator actually shows as the previously picked speed is stuck, instead of showing the new and current / correct and actual one, for example, sometimes when I at first choose 2.0x, then switch to 1.8x and then to 1.4x or 1.6x, a wrong previous value will be wrongly reported/shown/displayed.

**Comment by drogga** [comment]
The duration / runtime of the Shorts is shown as 0:00 (or "0:0-1") in channel's/videos tab, but shown correctly in the feed, but it's the exact opposite for past (recorded) live streams, their duration is shown inside the channels, but not in the feed.

**Comment by drogga** [comment]
I don't see a point in those [Thumbs Up 100%] indicators on all the feed videos...

When clicking on a timestamp that is mostly provided in the description of longer videos, it just opens the same video on top of the current one in a new player window that plays simultaneously alongside that one, but also plays from the beginning, instead of jumping to that time point.
