### ISSUE TITLE
SponsorBlock support

### ISSUE THREAD

**Issue by Skjold** [SkyTubeTeam/SkyTube#892]
Hi,
I suggest adding support for [SponsorBlock](https://sponsor.ajay.app/), they have an open API and it was already integrated on Android by the YouTube Vanced project. This would add significantly to SkyTube's appeal.

**Comment by gzsombor** [comment]
That would be definitely be a nice new feature!

**Comment by SunflowerFuchs** [comment]
Just a small update, vanced was [announced dead today](https://twitter.com/YTVanced/status/1503052250268286980), so this might be the feature that decides for many people what app to switch to in the aftermath.

**Comment by TAImatem** [comment]
Returnyoutubedislikes would also be appreciated
