### ISSUE TITLE
playing video crash an app

### ISSUE THREAD

**Issue by overtube** [SkyTubeTeam/SkyTube#893]
After push for any video for playing, app is crash, version 2.975 working
perfect well, this bug only in 2.976 this tested on armv7l, armhf

**Comment by gzsombor** [comment]
Could you please explain it a bit more, how could you trigger the error? What have you clicked, what was the video, etc...

**Comment by drogga** [comment]
Fixed in 2.977 (probably), @overtube you are using the older buggy version, please update and learn better english !
I think this can be closed...

**Comment by gzsombor** [comment]
@drogga : good question, I don't know. I guess, only @ram-on can grant you rights.

**Comment by drogga** [comment]
@ram-on where are you at bro, we need you... :-)
_BTW - I can't even add label(s) to my own "issues" in other repos, the ones that are still open, I created them\I'm author of and are still without a label._

**Comment by ram-on** [comment]
Hello guys.  Since I am not active here and I do not know who is actively contributing and who is not, @gzsombor please let me know if you want to grant access to @drogga.

**Comment by gzsombor** [comment]
I'm closing as an already fixed bug.
