### ISSUE TITLE
Videos no longer play

### ISSUE THREAD

**Issue by arkdae** [SkyTubeTeam/SkyTube#910]
Starting today, selecting any video results in:

**Video Playback Error**
An error has occurred while retrieving video's streams.

**Comment by gzsombor** [comment]
Could you please include:
* A video URL where it can be reproduced?
* the version of the app? Is it the latest?
* do you get from F-Droid or from Github?
* Is it the OSS or the Extra version?
* Is your phone rooted?
* Do you use Tor or any VPN service with your phone?

**Comment by arkdae** [comment]
Sorry, since it occurs for every single video, whether in feed, featured, bookmark, etc., I assumed it would be easy to recreate. I'll try to get a URL.

For now, I'm running 2.975, from F-Droid, which shows as the latest. My Lenovo Yogabook running Android 7.1.1 is not rooted, though the bootloader is unlocked. I am not accessing via any VPN.

**Comment by arkdae** [comment]
https://youtu.be/qeBYzTr8_Ls

just a random video from the featured tab.

**Comment by gzsombor** [comment]
Please update to 2.977 - it's on F-Droid already: https://f-droid.org/en/packages/free.rm.skytube.oss/

**Comment by arkdae** [comment]
Sorry, I must have an issue with F-Droid. It looks like it is set to update daily, but there were a large number of updates after I manually refreshed.

Regardless, I still can't view any video. It says now:

**VIideo Playback Error**
reCaptcha Challenge requested

**Comment by arkdae** [comment]
Just to be clear, I am now running version 2.977 (2021-01-27 18:37)

**Comment by arkdae** [comment]
I think this is a New Pipe issue. I see a similar problem with it. I'm running New Pipe 0.20.1. I see that there is a 0.20.8 version available, but oddly it is not on F-Droid, even as their web site promotes F-Droid. I'm going to attempt to upgrade outside of F-Droid.

**Comment by arkdae** [comment]
I've manually uninstalled New Pipe 0.20.1, and installed 0.20.8 downloaded directly from New Pipe's web site. From within New Pipe, I was able to solve the reCaptcha myself, and now it plays the video (the very one linked above).

I rebooted my Android tablet in case the New Pipe library in use by SkyTube is cached as the old version. I have confirmed that I have "Use the NewPipe backend" checked in the preferences. Yet, the request to fill out a reCaptcha still exists with SkyTube, and provides no way of doing so.

Going back to New Pipe after the reboot, I was able to play videos and it did not ask for the reCaptcha a second time.

**Comment by gzsombor** [comment]
Thanks for checking it!

Yes, currently it is not possible to solve reCaptchas from SkyTube, however - as far as I know - after you've solved reCaptcha from your device, SkyTube will work again. Getting this error usually means, that from your IP address, there were a lot of requests recently, or your IP belongs to some suspicious range. I only saw this kind of error, when someone use VPN or Tor, or on corporate/university network.
 Btw, SkyTube has it's internal NewPipeExtractor library, so if you uninstall/reinstall/etc NewPipe it doesn't change anything in SkyTube's behaviour.

**Comment by gzsombor** [comment]
I've opened a separate ticket about reCaptchas: #912

**Comment by arkdae** [comment]
Thanks for the info. For sure I'm not on a VPN. Maybe someone else in the house was watching a variety of YouTube videos. Anyway, this morning I tried a video and it works without requesting reCaptcha. Next time it occurs, I'll try going directly to YouTube from Firefox on this same device and see if I can solve the reCaptcha that way, and get SkyTube back to functional.
