### ISSUE TITLE
Chinese simplified translation added.

### ISSUE THREAD

**Issue by ohsorry** [SkyTubeTeam/SkyTube#913]
Hey guys, after using SkyTube for the first time, I immediately added a simplified Chinese translation on weblate. Do I need to do anything else to submit translation resources?

**Comment by gzsombor** [comment]
Thanks ohsorry for your contribution! 

You don't need to do anything, the translations are all merged into the app, at least before a new release is created :+1:

**Comment by ohsorry** [comment]
Dude, noticed that the new version has been released, please add my github link (https://github.com/ohsorry) on the about page of the App, thank you.
Chinese simplified translation - by ohsorry is fine.
@gzsombor

**Comment by gzsombor** [comment]
Sorry man! When I write the changelogs, I work from the git commit logs, and if the author looks as, that someone wants to be anonym, I skip their name. And in this case, someone called as 'nproxy.org' felt in this category. But now, I've updated the release notes!

**Comment by ohsorry** [comment]
:smile: :smile: Thank you! Let's delete your last comment or this issue.
