### ISSUE TITLE
App crash, while SkyTube loading a search history.

### ISSUE THREAD

**Issue by KPniX** [SkyTubeTeam/SkyTube#916]
I found a bugs.
How I want to search a film on SkyTube 2.977 (from F-droid) on Alcatel Pixi 7 (Android 4.4.2) the app is chashing, while app loading a last search history and on films (movies) isn't sound (speakers on 100%).
And on Sony Xperia E dual (A 4.0.4) SkyTube 2.977 (from F-droid) is crashing, while it loading a UI (user interface) and on older version chashing, while a loading films player.
But for example on Android 4.4.2 on other phone app works on 99%.
Please on quick fix this bug.
(Sorry for many mistakes)

**Comment by gzsombor** [comment]
The crash with with Android 4.0.4 is fixed recently by me, however, I haven't seen problems with search history loading, and based on your description, I can't reproduce it. Could you send logs from your device? With adb logcat for example ?

**Comment by gzsombor** [comment]
I fixed a couple of bugs for v2.978 around the search history, please re-test it.
