### ISSUE TITLE
2 "broken" channels cause the app to sudddenly close

### ISSUE THREAD

**Issue by ValentinBr** [SkyTubeTeam/SkyTube#921]
**Describe the bug**
I have a list of about 150 channels I subscribed to, from Skytube. Some weeks ago, the app started to crash everytime I was refreshing the feed. I looked into the list with subscribed channels, and 2 of the channels were not loading the thumbnail of the channel. I tried to click on each of them and everytime i did that, the app was crashing. 

Unfortunately I don't know which are these 2 channels and I can't seem to be able to open the exported file (exported_file.skytube)

**Is there anything I can do to make Skytube refresh the Feed without crashing?**

It would be useful to be able to delete the channels from the list of channels, or at least to export and import the list of channels in a txt format (so we can edit it).

**Expected behavior**
Refresh the the Feed without the app crashing.

**Screenshots**
See the first 2 channels in the list (they don't have the thumbnail loaded and if clicked, the app crashes):
![skytube_bug](https://user-images.githubusercontent.com/51698041/107772189-94685000-6d44-11eb-9d73-8cea71f763e7.jpg)

**Setup:**
 - Android version: 10 (LineageOS)
 - Is Your device rooted? - No
 - Do You use Tor or any VPN service with your device? - No
 - App source: FDroid
 - App Version: v2.977
 - App Flavour: ?

**Comment by ValentinBr** [comment]
Anyone has any idea what can be done to get rid of those two broken channels and be able to refresh the Feed again ?

**Comment by drogga** [comment]
https://github.com/SkyTubeTeam/SkyTube/issues/934
