### ISSUE TITLE
Please add control play and pause remote controller

### ISSUE THREAD

**Issue by clevertype** [SkyTubeTeam/SkyTube#936]
Please add control play and pause remote controller on smart tv. The previous player in the settings supports but does not disappear the interface during playback.

**Comment by darksworm** [comment]
User story: When sending play/pause events from remote devices (headphones, remote control, etc) i expect the video playback to be paused/resumed.

It's likely to be to do with this [intent](https://developer.android.com/reference/android/content/Intent#ACTION_MEDIA_BUTTON).

---

I really want this for myself and I also have an android TV to test this on - I'd be happy to take this issue on.

**Comment by gzsombor** [comment]
Feel free to work on it, unfortunately the app is pretty bad in reacting external events - media keys, or network changes, or headphones disconnecting, any improvements are welcomed!
