### ISSUE TITLE
[Documentation] Don't use suggestive image in documentation

### ISSUE THREAD

**Issue by tsmethurst** [SkyTubeTeam/SkyTube#938]
Hi, I recently recommend your app to someone, and they pointed out to me that some of the images you use in your documentation are extremely racially insensitive, which I hadn't noticed since I just downloaded your app when looking through F-Droid for a youtube alternative. The image I'm referring to is this one: https://skytube-app.com/assets/img/screenshots/trending.jpg (an image of a white man choking a black man against a US flag).

I know it's from a music video and all, and maybe it just happened to be at the top of the Trending list when you made the documentation, and maybe it was an accident that you included this image. But it seems extremely racially insensitive to me to include an image of anti-Black violence in the documentation/advertising for your app. Can you address this?

**Comment by Joe23232** [comment]
We don't need to bring politics into technology.

**Comment by tsmethurst** [comment]
> We don't need to bring politics into technology.

1. Technology is already political whether you want it to be or not.
2. I'm not asking for a grand statement, I'm requesting a small documentation change for the sake of sensitivity and inclusiveness. This seems extremely reasonable to me.

If changing one image for the sake of not alienating a chunk of potential users is too much to ask, I can only assume that having that image present in the documentation is the racist dogwhistle I feared it might be.

**Comment by Joe23232** [comment]
The Internet if filled with a lot of terrible things (including YouTube itself), if you easily get offended then you should refrain yourself from using the Internet. Honestly political correctness is so bad that it has gotten women in the UK raped.

I am sick and tired of putting up with the left trying to even interfere with my own personal projects just because it asks a genders question (are you a male or female) all in the name of _feelings_. We don't need political correctness, it destroys everything.

As Linus Torvalds (founder of The Linux Project) said, he has seen projects that have gone too political that the project no longer is about itself anymore. I trust that man, he is a great blessing and a genius.

Oh by the way I am a black person and I don't need anyone to bring us "over protection" thank you very much!

**Comment by gzsombor** [comment]
Hi @tsmethurst !

 Unfortunately I don't know how to update the website - neither by the way, how to update the pictures in f-droid - it's managed by @ram-on who is not active in the project, and I guess, he is not even subscribed to the issues/comments here. 
 If you send pull request with new screenshots, I can merge them, so at least, at github, the problem will be resolved.

**Comment by tsmethurst** [comment]
Hi @gzsombor, thanks for the reply. I checked in the 'screenshots' subdir of this repo but none of those are the screenshot in question, and I don't see a repo for the website unfortunately. So I can't make a PR that will fix this.

I'll close this issue now since there's apparently nothing I can do.

**Comment by jmichael2497** [comment]
i came from finding NewPipe and SkyTube as most recent YouTube alternative apps in F-Droid but was also shocked to see the leading image of a young white male skinhead choking a black man against an american flag... wow, that was quite the choice, with many chances to notice, realize, and change it to something else.

somebody tried to say asking to change this is bringing in politics, wrong, politics were brought in when someone decided that was totally fine to have screenshots with clear racist violence. it would be just as inappropriate to feature non-racist violence, sex, nsfw etc content.

make better choices. considering this was called out over a year ago, that is a clear series of reinforced choices. it doesn't take a dev to right-click and follow the source trails from the README.md to the github hosted website, and obviously the standard Fastlane folder where app descriptions are stored.

look what i found in under half hour to be thorough:
```
README.md screenshots section has relevant links
(https://github.com/SkyTubeTeam/SkyTube/blob/master/README.md)

https://skytube-app.com/assets/img/screenshots/trending.jpg
(https://github.com/SkyTubeTeam/SkyTube/blob/gh-pages/assets/img/screenshots/trending.jpg)
(https://github.com/SkyTubeTeam/SkyTube/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/1-trending.jpg)

https://skytube-app.com/assets/img/screenshots/subs.jpg
(https://github.com/SkyTubeTeam/SkyTube/blob/gh-pages/assets/img/screenshots/subs.jpg)
(https://github.com/SkyTubeTeam/SkyTube/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/3-subs.jpg)
```

so make a new phone screenshot for "trending" and "subscriptions" to replace those 4 files named, and that solves most of the problem. not sure of the process to bump F-Droid to update, but can't be that hard to run a search and find the answer or at least a forum to send a question message 🤷🏽‍♂️

**Comment by jmichael2497** [comment]
> Could you please send a pull request to add new screenshots?

i have no reason to start using an app just to help remove 4yo racist imagery, when this could and should have been handled by anyone who has already been using the app, and could get this done quickly.

f-droid already lists long existing prior options of NewPipe (so i installed that), and it also lists another option of LibreTube anyway.
