### ISSUE TITLE
Hi how does this app differ to NewPipe?

### ISSUE THREAD

**Issue by Joe23232** [SkyTubeTeam/SkyTube#945]
Hi how does this app differ to [NewPipe](https://newpipe.net/)? Is SkyTube more or less privacy oriented compared to NewPipe?

**Comment by gzsombor** [comment]
If you open both app, you will see the similarities and differences on the UI. Of course the code base is similarly different, however both app use NewPipeExtractor to access Youtube. Historically, SkyTube mostly used the official YouTube API, which had a couple of advantages, but as more and more people started using SkyTube the problems were shadowed the advantages, so the direct YouTube API have been reduced, but there are places, where it still need it. And you can use ChromeCast and the offical Youtube Player component in SkyTube, both need non-free code, so SkyTube Extra is not a 100% FOSS application.
 I don't think I can judge or compare the privacy orientedness of the two projects.
