### ISSUE TITLE
Serious! Error is occurred while fetching a more videos from any YouTube Channel 

### ISSUE THREAD

**Issue by satsang-katha** [SkyTubeTeam/SkyTube#948]
**Describe the bug**

Error is occurred while try to fetch more videos from any YouTube Channel (e.g. Android Developer).
Please see the Description along with Video(link) , Screenshot and error_log.txt for more info about, How this is occurred.

**To Reproduce**

1. Go to ' search any YouTube Channel (e.g. Android Developer)'
2. Click on 'Channel which is displayed'
3. Scroll down to 'For More videos from the channel in video tab'

**Expected behavior**

More Videos are expected to fetch by app.

**Error Log File**
[error_log.txt.txt](https://github.com/SkyTubeTeam/SkyTube/files/6237908/error_log.txt.txt)

**Video Link**
https://drive.google.com/file/d/1YbGJxfWULaAOQCTZJttrIZWSVhHKIsmE/view?usp=sharing

**Screenshots**
Screenshot at time of Error is to help explain  problem where You've found the issue.

![InkedScreenshot_2021-03-31-20-30-22-979_com miui videoplayer_LI](https://user-images.githubusercontent.com/78640423/113179612-71025180-926d-11eb-9f81-df7dcd1501ff.jpg)

**Setup:**
 - Android version: 7.0
 - Is Your device rooted? : No
 - Do You use Tor or any VPN service with your device? :No
 - App source [e.g. FDroid, Downloaded from GitHub, self build] : GitHub/Debug
 - App Version : 2.978
 - App Flavour [e.g. Extra or OSS]

**Additional context**
Please Solve this issue ASAP.

Thanking You.
Yours Big Fan.

**Comment by gzsombor** [comment]
It's fixed with #966
