### ISSUE TITLE
Add please autostart next video option

### ISSUE THREAD

**Issue by clevertype** [SkyTubeTeam/SkyTube#952]
Add please autostart next video after ending (option in settings enable/disable).

**Comment by gzsombor** [comment]
There are a couple of trickier question lies behind:
* how to decide what is the next video? Use Youtube's suggestions - if network is available, etc? Or pick the next downloaded video? Or pick the next unseen video from the same channel? 
* do we want to present a selector of X videos to the user before showing the next? 
* etc

**Comment by gzsombor** [comment]
It's the duplicate of : #648
