### ISSUE TITLE
SkyTube can't see OPML file with YouTube subscriptions

### ISSUE THREAD

**Issue by vladimirpol** [SkyTubeTeam/SkyTube#977]
When I try to import my subscriptions in SkyTube 2.978 from the file "youtubeSubscriptions.opml" I exported before from my YouTube account - I just can't see it in import window. Am I doing something wrong?

**Comment by ChunkyProgrammer** [comment]
I took a quick look at the SkyTube source code and it looks like it only supports importing "json" subscriptions (youtube replaced exported opml files with json and recently replaced exporting json with csv files).

**Comment by gzsombor** [comment]
Yes, this is true, currently only the json import is supported, sad, that YouTube changed again.
