### ISSUE TITLE
Default player stopps every 10 seconds

### ISSUE THREAD

**Issue by Spielmops** [SkyTubeTeam/SkyTube#990]
**Describe the bug**
The default player stopps every about 10 seconds for a few seconds. At first the problem seems to be a bad internet-connection. But a test with Newpipe confirms: it's not the connection. 

I then changed in "Settings" the videoplayer from "default" to " legacy" and Skytube played without stoping.

I tested this on 2 tablets and 3 smartphones, all with LineageOS, versions range from 14 to 18. All devices are able to play everything with VLC and Newpipe without problems.

Spielmops

**Comment by gzsombor** [comment]
Please test with the latest release, it uses the latest NewpipeExtractor
