### ISSUE TITLE
Youtube inport Takeout

### ISSUE THREAD

**Issue by bodziopolska** [SkyTubeTeam/SkyTube#991]
Hello, I have a problem because if I want to import subscriptions from youtube, if I download rar, instead of .jsom I have .csv

**Comment by cangSDARM** [comment]
Follow this: https://jsbin.com/pegiloviza/2/edit?html,js,output

Notice:
- replace exported the first line of the csv file to `service_id,url,name`
- replace above code
![image](https://user-images.githubusercontent.com/20441896/131647992-bceb4661-f9a8-4e2e-8b18-9bca291a2c46.png)
to 
![image](https://user-images.githubusercontent.com/20441896/131648049-1d72c72e-55fe-4f3b-8bd9-b02dc8f6a63c.png)
- And maybe still fault, replace `"app_version": "0.21.8", "app_version_int": 974,` to one line.<br/> (I don't know why, but it works. If not, replace those things from skytube/newpipe exported file).

It's worked in the newest newpipe.
